# -*- coding: utf-8 -*-
"""MangoDeteccion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OcYoRHXJDItos4LrZ4mHML-Qi8IHwpgY
"""

!pip install roboflow ultralytics

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="WfcsbaSfguy8X4dvHPwT")
project = rf.workspace("mangodetection-q9bue").project("detecctionmango")
version = project.version(3)
dataset = version.download("yolov11")

from ultralytics import YOLO
model = YOLO("yolo11s.pt")

data_path = "/content/detecctionMango-3/data.yaml"
results = model.train(data=data_path,
                      epochs=30,
                      imgsz=640)

# Cargamos el modelo ya entrenado
custom_model = YOLO("/content/runs/detect/train/weights/best.pt")

# Realizamos predicciones sobre algunas imágenes
res = custom_model("/content/detecctionMango-3/test/images")

# Visualizamos los resultados de las detecciones
res[37].show()

